# Generated by Django 6.0.5 on 2026-05-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verify',
            new_name='is_verified',
        ),
    ]
