# Generated by Django 6.0.5 on 2026-05-23 15:01

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_is_verify_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default=9919792742,
                max_length=12,
                validators=[accounts.validators.validate_iranian_cellphone_number],
            ),
            preserve_default=False,
        ),
    ]
