# Generated by Django 6.0.5 on 2026-05-23 15:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_review_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["created_date"]},
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_main",
        ),
        migrations.AddField(
            model_name="category",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="avg_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[(1, "نمایش"), (2, "عدم نمایش")], default=2
            ),
        ),
        migrations.CreateModel(
            name="WishlistProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
