# Generated by Django 6.0.5 on 2026-06-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="order.ordermodel",
            ),
        ),
    ]
